spring:
  application:
    name: binance-data-provider
  banner: classpath:/banner-binance-data-provider.txt
  cloud:
    vault:
      uri: https://localhost:8200
      scheme: https
      host: localhost
      port: 8200
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      tls:
        enabled: true
      kv:
        enabled: true
